apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-api-sa
  namespace: app
  annotations:
    # Paste the irsa_role_arn Terraform output here
    eks.amazonaws.com/role-arn: arn:aws:iam::844074033173:role/mlops-dev-bedrock-irsa-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
  namespace: app
  labels:
    app: rag-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      serviceAccountName: rag-api-sa
      containers:
        - name: rag-api
          # Push your image to ECR and reference it here, e.g.
          # <account_id>.dkr.ecr.ap-south-1.amazonaws.com/rag-api:latest
          image: "844074033173.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest"
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: "ap-south-1"
            - name: KNOWLEDGE_BASE_ID
              value: "GPIIZYUCQU"
            - name: MODEL_ID
              value: "amazon.nova-lite-v1:0"
            - name: DYNAMODB_TABLE
              value: "mlops-conversations"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
